/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#include "ModMPGamePrivate.h"

IMPLEMENT_PACKAGE(ModMPGame)



IMPLEMENT_CLASS(AAdminService);
FNativeEntry<AAdminService> AAdminService::StaticNativeMap[] = {
	MAP_NATIVE(ParseCommand,0)
	MAP_NATIVE(ParseToken,0)
	MAP_NATIVE(ParseIntParam,0)
	MAP_NATIVE(ParseFloatParam,0)
	MAP_NATIVE(ParseStringParam,0)
	MAP_NATIVE(ExecCmd,0)
	MAP_NATIVE(EventLog,0)
	{NULL,NULL}
};
LINK_NATIVES(AAdminService);

IMPLEMENT_CLASS(ABotSupport);

IMPLEMENT_CLASS(ACombatLogger);
FNativeEntry<ACombatLogger> ACombatLogger::StaticNativeMap[] = {
	MAP_NATIVE(LogEvent,0)
	{NULL,NULL}
};
LINK_NATIVES(ACombatLogger);

IMPLEMENT_CLASS(AMatchManager);
FNativeEntry<AMatchManager> AMatchManager::StaticNativeMap[] = {
	MAP_NATIVE(SetPlayerReadyState,0)
	MAP_NATIVE(GetPlayerReadyState,0)
	{NULL,NULL}
};
LINK_NATIVES(AMatchManager);

IMPLEMENT_CLASS(ASkinChanger);
FNativeEntry<ASkinChanger> ASkinChanger::StaticNativeMap[] = {
	MAP_NATIVE(SetCloneSkin,0)
	MAP_NATIVE(SetTrandoSkin,0)
	{NULL,NULL}
};
LINK_NATIVES(ASkinChanger);

IMPLEMENT_CLASS(AMPBot);
FNativeEntry<AMPBot> AMPBot::StaticNativeMap[] = {
	MAP_NATIVE(UpdatePawnAccuracy,0)
	{NULL,NULL}
};
LINK_NATIVES(AMPBot);

IMPLEMENT_CLASS(AAdminControl);
FNativeEntry<AAdminControl> AAdminControl::StaticNativeMap[] = {
	MAP_NATIVE(EventLog,0)
	MAP_NATIVE(SaveStats,0)
	MAP_NATIVE(RestoreStats,0)
	MAP_NATIVE(ResetAllStats,0)
	{NULL,NULL}
};
LINK_NATIVES(AAdminControl);

IMPLEMENT_CLASS(APatrolPoint);

IMPLEMENT_CLASS(ASmallNavigationPoint);

IMPLEMENT_CLASS(AInventorySpot);
